apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricflow-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metricflow
  template:
    metadata:
      labels:
        app: metricflow
    spec:
      containers:
        - name: metricflow
          image: tani1964/metricflow:latest
          ports:
            - containerPort: 3000
          env:
            - name: TEMPORAL_ADDRESS
              value: "temporal:7233" 
---
apiVersion: v1
kind: Service
metadata:
  name: metricflow-service
spec:
  type: LoadBalancer
  selector:
    app: metricflow
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
