global:
  scrape_interval: 1s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'temporal-workflow'
    static_configs:
      - targets: ['metrics-server:3000']
    metrics_path: '/metrics'
    scrape_interval: 1s

  - job_name: 'temporal-server'
    static_configs:
      - targets: ['temporal:7233']
    metrics_path: '/metrics'
    scrape_interval: 4s



    