apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: newwave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        # image: postgres:13
        image: postgres:13
        # image: quay.io/postgres/postgres:13-alpine
        env:
        - name: POSTGRES_DB
          value: "temporal"
        - name: POSTGRES_USER
          value: "temporal"
        - name: POSTGRES_PASSWORD
          value: "temporal"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U temporal -d temporal
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U temporal -d temporal
          initialDelaySeconds: 30
          periodSeconds: 30
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: newwave
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP