apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: temporal-workflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
      - name: temporal-server
        image: temporalio/auto-setup:1.22.0
        ports:
        - containerPort: 7233
        - containerPort: 8233
        env:
        - name: DB
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: POSTGRES_SEEDS
          value: "postgres.temporal-workflow.svc.cluster.local"
        - name: POSTGRES_USER
          value: "temporal"
        - name: POSTGRES_PWD
          value: "temporal"
        - name: POSTGRES_DB
          value: "temporal"
        - name: ENABLE_ES
          value: "false"
        - name: SKIP_SCHEMA_SETUP
          value: "false"
        resources:
          limits:
            memory: "1Gi"
            cpu: "500m"
          requests:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 7233
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-server
  namespace: temporal-workflow
spec:
  selector:
    app: temporal-server
  ports:
  - name: grpc
    port: 7233
    targetPort: 7233
  - name: http
    port: 8233
    targetPort: 8233